# 基本・ポインティング機能
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y

# 無線・システム設定
CONFIG_ZMK_BLE=y
CONFIG_NFCT_PINS_AS_GPIOS=y

# トラックボール用SPI・ドライバ設定
CONFIG_SPI=y
CONFIG_PMW3610=y
CONFIG_PMW3610_INVERT_X=n
CONFIG_PMW3610_SMART_ALGORITHM=y
CONFIG_PMW3610_REPORT_INTERVAL_MIN=12

# バッテリー報告機能
CONFIG_ZMK_BATTERY_REPORTING=y
