CONFIG_ZMK_POINTING=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_MOUSE=y

CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_INPUT_PMW3610=y

CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_RGBLED_WIDGET=y

# 💡 安全にスリープを無効化し、Bluetoothの電波だけを強くする
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_IDLE_TIMEOUT=3600000
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
